Add Polly, basic retry policy, extension methods for HttpClient
gettyimages/gettyimages-api_dotnet pull request #28
Opened 2021-06-18 22:30 UTC by ChrisSimmons

Add Polly and general retry policy for transient errors (e.g. 500, 408, 429).

2021-06-18 22:34 UTC, ChrisSimmons commented on GettyImages.Api/WebHelper.cs
> -                    Task.Delay(1000).Wait();
Using the retry policy should eliminate the need for these manual delays as well.

2021-06-18 22:35 UTC, ChrisSimmons commented on GettyImages.Api/WebHelper.cs
> +                            httpResponse = await retryClient.PostAsyncWithRetryPolicy(uri, formContent);
I'm re-using `formContent` here instead of `new`-ing up a `FormUrlEncodedContent` again.  Any issues there?

2021-06-18 22:40 UTC, ChrisSimmons commented on GettyImages.Api/WebHelper.cs
> -                        httpResponse = await retryClient.PostAsync(uri, new FormUrlEncodedContent(queryParameters));
I think this is a bug as the `UnauthorizedException` retry doesn't make use of `bodyParameter`.  I've left the call as-is in the new "`WithRetryPolicy`" form but filed a bug on the underlying issue here: https://github.com/gettyimages/gettyimages-api_dotnet/issues/27

2021-06-18 22:40 UTC, ChrisSimmons commented on GettyImages.Api/WebHelper.cs
> -                        httpResponse = await retryClient.PutAsync(uri, new FormUrlEncodedContent(queryParameters));
Same deal here, not using `bodyParameter` on the `UnauthorizedException` retry.  See comment above.

2021-06-19 00:12 UTC, ChrisSimmons commented
I'd actually like to have #29 merged or closed before doing this.  Setting this to draft.

2021-06-22 17:03 UTC, ssterli2 approved these changes

2021-06-29 20:15 UTC, mapitman requested changes
Just the one minor change i commented on.

2021-06-29 20:15 UTC, mapitman commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
I think 2 seconds may be a little too long for the wait time. Especially if it has to retry a second or third time, it could end up being 14 seconds in total!

2021-06-29 21:17 UTC, ChrisSimmons commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
Thoughts on other options?  I don't really know what the "right" choice is here.

```
// Up to 3 secs
TimeSpan.FromSeconds(retryAttempt * 0.5)
```

```
// Up to 6 secs
TimeSpan.FromSeconds(retryAttempt)
```

```
// Up to 9 secs
TimeSpan.FromSeconds(retryAttempt * 1.5)
```

2021-06-29 21:18 UTC, ChrisSimmons commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
I imagine we should release with some "sane" hard-coded setting and then look into allowing some optional configuration.

2021-06-29 21:23 UTC, ChrisSimmons commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
I pushed up a 1s, 2s, 3s (6s possible total) version.  Let me know if you agree.

2021-06-29 21:50 UTC, mapitman commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))
I'd say start at  either 100 ms or 500 ms at the most.

2021-06-29 23:23 UTC, mapitman commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(retryAttempt)
How about `TimeSpan.FromMilliseconds(retryAttempt * 100)` ?

2021-06-30 23:28 UTC, ChrisSimmons commented on GettyImages.Api/PollyHttpClientExtensions.cs
> +                        TimeSpan.FromSeconds(retryAttempt)
Done

2021-06-30 23:30 UTC, ChrisSimmons reviewed
I think I've covered the concerns

2021-06-30 23:37 UTC, mapitman approved these changes
Looks good.

2021-06-30 23:50 UTC, merged